// const theme = require("./src/design-system/tailwind-design")

// const { fontSize, fontFamily } = theme;

module.exports = {
  theme: {
    // If you want to override default tailwind values with your own set of values, then put them here

    extend: {
      // Here you can extend values generated by default.
    },
  },
  variants: {},
};
